apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ssatish.gonella@gmail.com # Replace with your email
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        cloudflare:
          email: ssatish.gonella@gmail.com # Replace with your Cloudflare email
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
